// <auto-generated />
using System;
using GibGameDatabase.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GibGameDatabase.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20220214131724_make-igdbid-nullable")]
    partial class makeigdbidnullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("GibGameDatabase.Models.FailedEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HolId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FailedGameEntries");
                });

            modelBuilder.Entity("GibGameDatabase.Models.GameEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoxImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hardware")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("HolId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IgdbGameAndPlatformId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NoOfDisks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GameEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
